name: deploy-ghpage
run-name: building lektor pages
on: [push]
jobs:
  deploy-lektor-ghpage:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install "Flask<2"
      - run: pip install Lektor
      - run: lektor build
      - run: lektor deploy ghpages
